name: Build & Release Debian Package

on:
  push:
    tags:
      - 'v*'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: ğŸ“¥ Checkout repository
        uses: actions/checkout@v4

      - name: âš¡ Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          version: "latest"

      - name: ğŸ Set up Python
        run: uv python install

      - name: ğŸ“¦ Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            gobject-introspection \
            libgirepository-2.0-dev \
            libglib2.0-dev \
            libffi-dev \
            gir1.2-gtk-3.0 \
            libcairo2-dev \
            pkg-config \
            python3-dev \
            libwebkit2gtk-4.1-dev \
            wkhtmltopdf

      - name: ğŸ“¦ Install Python dependencies
        run: uv sync

      - name: â¬‡ï¸ Download frontend libraries
        run: |
          chmod +x scripts/download_front_libs.sh
          ./scripts/download_front_libs.sh

      - name: ğŸ“¦ Build Debian package
        run: |
          chmod +x scripts/make_deb.sh
          ./scripts/make_deb.sh

      - name: ğŸš€ Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            *.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}